---
- name: Mount drives and add to fstab
  hosts: all

  tasks:
    - name: Mount drives to fstab
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: "{{ item.fstype }}"
        state: mounted
        boot: true
      with_items: "{{ drives }}"
