- name: Install Node Exporter
  hosts: all
  any_errors_fatal: true

  tasks:
    - name: Download node-exporter binaries
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-arm64.tar.gz
        dest: /tmp/node-exporter.tar.gz
        mode: "0600" # U:RW, G:N, O:N

    - name: Unzip the node-exporter binaries
      ansible.builtin.unarchive:
        src: /tmp/node-exporter.tar.gz
        dest: /tmp
        remote_src: true

    - name: Copy over node-exporter binary
      ansible.builtin.copy:
        src: /tmp/node_exporter-1.10.2.linux-arm64/node_exporter
        dest: /opt
        remote_src: true
        mode: "0700" # U:RWX, G:N, O:N

    - name: Copy over systemd file
      ansible.builtin.copy:
        src: files/node-exporter.service
        dest: /etc/systemd/system/node-exporter.service
        remote_src: false
        mode: "0600" # U:RW, G:N, O:N

    - name: Start node-exporter system
      ansible.builtin.systemd_service:
        name: node-exporter
        daemon_reload: true
        enabled: true
        state: restarted
