apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yml

patches:
  - target:
      kind: Service
      name: argocd-server
    path: service-patch.yml
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --insecure
    target:
      kind: Deployment
      name: argocd-server